### ISSUE TITLE
Could you please provide me with the script that generates your data

### ISSUE THREAD

**Issue by Jeozhao** [liweileev/FET-GAN#1]
@liweileev Nice to see what you do, your work is really interesting.  I have some doubts about the generation of your dataset, Could you please provide me with the script that generates your data. 
Thank you very much!

**Comment by liweileev** [comment]
The TextEffects Dataset is proposed in (Yang et al. 2019).

Yang, S.; Liu, J.; Wang, W.; and Guo, Z. 2019. TET-GAN: Text effects transfer via stylization and destylization. In Proceedings of the AAAI Conference on Artificial Intelligence (AAAI), volume 33, 1238–1245.

For the Fonts-100, I created it using the batch processing function in photoshop.
